all: cyoa-step4 cyoa-step3 cyoa-step2 cyoa-step1
cyoa-step4: cyoa-step4.cpp story.cpp story.h
		g++ -ggdb3 -Wall -Werror -pedantic -o cyoa-step4 cyoa-step4.cpp story.cpp
cyoa-step3: cyoa-step3.cpp story.cpp story.h
		g++ -ggdb3 -Wall -Werror -pedantic -o cyoa-step3 cyoa-step3.cpp story.cpp
cyoa-step2: cyoa-step2.cpp story.cpp story.h
		g++ -ggdb3 -Wall -Werror -pedantic -o cyoa-step2 cyoa-step2.cpp story.cpp
cyoa-step1: cyoa-step1.cpp story.cpp story.h
		g++ -ggdb3 -Wall -Werror -pedantic -o cyoa-step1 cyoa-step1.cpp story.cpp
